# Generated by Django 6.0.1 on 2026-02-17 08:16

import api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10-digit number')])),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('consignee', 'Consignee'), ('truck_owner', 'Truck Owner'), ('transporter', 'Transporter'), ('corporate', 'Corporate'), ('admin', 'Admin'), ('driver', 'Driver')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=api.models.user_profile_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_logs',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pickup_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('delivery_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('driver_assigned', 'Driver Assigned'), ('at_pickup', 'At Pickup'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('at_delivery', 'At Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('eway_bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bilty_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_consignee', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_transporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='CorporateProfile',
            fields=[
                ('corporate_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporate_profiles',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_category', models.CharField(choices=[('damaged_goods', 'Damaged Goods'), ('late_delivery', 'Late Delivery'), ('payment_issue', 'Payment Issue'), ('vehicle_condition', 'Vehicle Condition'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('evidence_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.booking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('gst', 'GST'), ('dl', 'Driving License'), ('rc', 'RC'), ('fitness', 'Fitness'), ('insurance', 'Insurance')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_file', models.FileField(upload_to=api.models.kyc_document_upload_path)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('load_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('drop_address', models.TextField()),
                ('drop_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('drop_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('material_type', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_date', models.DateTimeField()),
                ('is_fragile', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('trip_mode', models.CharField(choices=[('full_truck', 'Full Truck'), ('tempopool', 'TempoPool')], default='full_truck', max_length=20)),
                ('booking_type', models.CharField(choices=[('instant', 'Instant'), ('bidding', 'Bidding')], default='instant', max_length=20)),
                ('budget_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(limit_choices_to={'role__in': ['consignee', 'corporate']}, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loads',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='load',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.load'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('system', 'System'), ('promo', 'Promo')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('otp', models.CharField(max_length=4)),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verification', 'Verification'), ('login', 'Login')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verifications',
                'indexes': [models.Index(fields=['phone_number', 'otp_type', 'is_used'], name='otp_verific_phone_n_dee69a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('paytm', 'Paytm'), ('cashfree', 'Cashfree'), ('cod', 'COD'), ('wallet', 'Wallet')], max_length=20)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('escrow_held', 'Escrow Held'), ('released_to_vendor', 'Released to Vendor'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('admin_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.booking')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.booking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_label', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_addresses',
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('tracking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('current_location_text', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='api.booking')),
            ],
            options={
                'db_table': 'shipment_tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('mini_truck', 'Mini Truck'), ('tempo', 'Tempo'), ('container', 'Container'), ('trailer', 'Trailer'), ('open_body', 'Open Body')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('registration_year', models.IntegerField(blank=True, null=True)),
                ('capacity_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role__in': ['truck_owner', 'transporter']}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bid_message', models.TextField(blank=True, null=True)),
                ('bid_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.load')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'db_table': 'bids',
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=api.models.vehicle_photo_upload_path)),
                ('side', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left', 'Left'), ('right', 'Right'), ('interior', 'Interior')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.vehicle')),
            ],
            options={
                'db_table': 'vehicle_photos',
            },
        ),
        migrations.CreateModel(
            name='VehicleSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('available_capacity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return'), ('tempopool', 'TempoPool')], default='one_way', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('booked', 'Booked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.vehicle')),
            ],
            options={
                'db_table': 'vehicle_schedules',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('reference_type', models.CharField(choices=[('booking_payment', 'Booking Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('penalty', 'Penalty')], max_length=20)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('user', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['pickup_lat', 'pickup_lng'], name='loads_pickup__0c4a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status'], name='loads_status_731c17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('booking', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner'], name='vehicles_owner_i_b73183_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status'], name='bookings_booking_ab1f8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('load', 'transporter')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclephoto',
            unique_together={('vehicle', 'side')},
        ),
        migrations.AddIndex(
            model_name='vehicleschedule',
            index=models.Index(fields=['start_lat', 'start_lng'], name='vehicle_sch_start_l_c9e903_idx'),
        ),
    ]
