# Generated by Django 6.0.1 on 2026-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='otp_verific_phone_n_dee69a_idx',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='otp_verific_email_164e1c_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('email_registration', 'Email Registration'), ('phone_registration', 'Phone Registration'), ('password_reset', 'Password Reset')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'otp_type', 'is_used', 'is_verified'], name='otp_verific_phone_n_338e48_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'otp_type', 'is_used', 'is_verified'], name='otp_verific_email_3d904f_idx'),
        ),
    ]
