# Generated by Django 6.0.1 on 2026-02-17 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_booking_ab1f8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='load',
            name='loads_status_731c17_idx',
        ),
        migrations.RenameField(
            model_name='kycdocument',
            old_name='document_file',
            new_name='file_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='profile_image_url',
        ),
        migrations.RenameField(
            model_name='vehiclephoto',
            old_name='photo',
            new_name='photo_url',
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='savedaddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicleschedule',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='vehicleschedule',
            name='price_per_km',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verification', 'Verification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10-digit number')]),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='load',
            name='updated_at',
        ),
    ]
