# Generated by Django 6.0.1 on 2026-02-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_otp_otp_verific_phone_n_dee69a_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('hamali', 'Hamali Payment'), ('loading', 'Loading Charges'), ('unloading', 'Unloading Charges'), ('handling', 'Handling Charges'), ('haulting', 'Haulting Charges'), ('local_delivery', 'Local Delivery'), ('waiting', 'Waiting Charges'), ('penalty', 'Penalty'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extra_charges',
            },
        ),
        migrations.CreateModel(
            name='FestivalGift',
            fields=[
                ('gift_id', models.AutoField(primary_key=True, serialize=False)),
                ('festival', models.CharField(choices=[('diwali', 'Diwali'), ('holi', 'Holi'), ('eid', 'Eid'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('other', 'Other')], max_length=20)),
                ('gift_type', models.CharField(choices=[('cash_bonus', 'Cash Bonus'), ('voucher', 'Gift Voucher'), ('physical', 'Physical Gift'), ('other', 'Other')], max_length=20)),
                ('gift_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gift_description', models.TextField()),
                ('minimum_rating', models.DecimalField(decimal_places=2, default=4.0, max_digits=3)),
                ('minimum_turnover', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'festival_gifts',
            },
        ),
        migrations.CreateModel(
            name='LoadRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weight_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('traffic_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'load_requests',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('penalty_type', models.CharField(choices=[('wrong_delivery', 'Wrong Delivery'), ('late_delivery', 'Late Delivery'), ('damaged_goods', 'Damaged Goods'), ('misbehavior', 'Driver Misbehavior'), ('cancellation', 'Late Cancellation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delay_minutes', models.IntegerField(blank=True, null=True)),
                ('delay_rate_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating_impact', models.IntegerField(default=0, help_text='Negative impact on rating (-1 to -5)')),
                ('visibility_reduction_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('applied', 'Applied'), ('waived', 'Waived'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'penalties',
            },
        ),
        migrations.CreateModel(
            name='PricingSlab',
            fields=[
                ('slab_id', models.AutoField(primary_key=True, serialize=False)),
                ('slab_type', models.CharField(choices=[('distance', 'Distance Based'), ('weight', 'Weight Based'), ('combined', 'Combined')], default='combined', max_length=20)),
                ('min_distance', models.IntegerField(default=0)),
                ('max_distance', models.IntegerField(blank=True, null=True)),
                ('min_weight_ton', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_weight_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_per_km', models.DecimalField(decimal_places=2, help_text='Rate per kilometer', max_digits=10)),
                ('rate_per_ton_km', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per ton per km (e.g., 20 MT per ton)', max_digits=10, null=True)),
                ('is_base_slab', models.BooleanField(default=False)),
                ('base_weight_kg', models.IntegerField(default=1000)),
                ('base_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_distance_for_part_load', models.IntegerField(default=5)),
                ('part_load_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('peak_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('festival_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_slabs',
                'ordering': ['min_distance', 'min_weight_ton'],
            },
        ),
        migrations.CreateModel(
            name='ReturnTripOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=255)),
                ('from_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('from_lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('to_location', models.CharField(max_length=255)),
                ('to_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('to_lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('available_space_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'return_trip_offers',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return'), ('tempopool', 'TempoPool')], default='one_way', max_length=20)),
                ('from_location', models.CharField(max_length=255)),
                ('from_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('from_lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination_lng', models.DecimalField(decimal_places=8, max_digits=10)),
                ('total_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_capacity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_return_trip_available', models.BooleanField(default=False)),
                ('return_from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('return_from_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('return_from_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('return_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('return_available_from', models.DateTimeField(blank=True, null=True)),
                ('return_available_to', models.DateTimeField(blank=True, null=True)),
                ('scheduled_boarding_time', models.DateTimeField()),
                ('actual_boarding_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField()),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time_commitment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_halted', models.BooleanField(default=False)),
                ('halt_start_time', models.DateTimeField(blank=True, null=True)),
                ('halt_end_time', models.DateTimeField(blank=True, null=True)),
                ('halt_location', models.CharField(blank=True, max_length=255, null=True)),
                ('halt_reason', models.TextField(blank=True, null=True)),
                ('original_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjusted_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate_adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('rate_adjustment_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('boarding', 'At Boarding Point'), ('in_transit', 'In Transit'), ('halted', 'Halted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('delay_reason', models.TextField(blank=True, null=True)),
                ('is_visible_to_consignee', models.BooleanField(default=True)),
                ('is_visible_to_transporter', models.BooleanField(default=True)),
                ('is_visible_for_return_search', models.BooleanField(default=False)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('location_history', models.JSONField(default=list, help_text='Track location history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trip_locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('mini_truck', 'Mini Truck'), ('tempo', 'Tempo'), ('container', 'Container'), ('trailer', 'Trailer'), ('open_body', 'Open Body')], max_length=20)),
                ('length_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacity_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_rate_per_km', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('base_distance_km', models.DecimalField(decimal_places=2, default=240, max_digits=10)),
                ('base_charge', models.DecimalField(decimal_places=2, default=7000, max_digits=10)),
                ('sample_rate_10ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_rate_16ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sample_rate_22ft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slab_config', models.JSONField(default=dict, help_text='Rate slabs configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_categories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bid',
            name='load',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='transporter',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='vehicle',
        ),
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='load',
            name='required_vehicle_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_time_commitment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_confirmed_before_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='is_deliverable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='load',
            name='is_price_auto_calculated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='load',
            name='price_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('return', 'Return')], default='one_way', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cash_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='annual_turnover',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='late_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='successful_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='visibility_score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='wrong_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='consumption_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='wallet',
            name='reward_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('driver_assigned', 'Driver Assigned'), ('at_pickup', 'At Pickup'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('at_delivery', 'At Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, db_column='driver_id', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason_category',
            field=models.CharField(choices=[('damaged_goods', 'Damaged Goods'), ('late_delivery', 'Late Delivery'), ('wrong_delivery', 'Wrong Delivery'), ('payment_issue', 'Payment Issue'), ('vehicle_condition', 'Vehicle Condition'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='load',
            name='drop_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='drop_lng',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='pickup_lng',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='load',
            name='trip_mode',
            field=models.CharField(choices=[('full_truck', 'Full Truck'), ('tempopool', 'TempoPool'), ('part_load', 'Part Load')], default='full_truck', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('load', 'Load'), ('system', 'System'), ('promo', 'Promo'), ('security', 'Security'), ('festival_gift', 'Festival Gift')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('email_registration', 'Email Registration'), ('phone_registration', 'Phone Registration'), ('password_reset', 'Password Reset'), ('delivery_otp', 'Delivery OTP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='reference_type',
            field=models.CharField(choices=[('booking_payment', 'Booking Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('penalty', 'Penalty'), ('reward', 'Reward'), ('cashback', 'Cashback')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('user', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status'], name='bookings_booking_ab1f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['consignee', 'booking_status'], name='bookings_consign_d6f5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['transporter', 'booking_status'], name='bookings_transpo_cef5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['driver', 'booking_status'], name='bookings_driver__0e8256_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='users_role_bc23be_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['plan_type', 'visibility_score'], name='users_plan_ty_5dcf68_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type', 'verification_status'], name='vehicles_vehicle_d58160_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleschedule',
            index=models.Index(fields=['status', 'available_from', 'available_to'], name='vehicle_sch_status_5a951a_idx'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='api.booking'),
        ),
        migrations.AddField(
            model_name='extracharge',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='festivalgift',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='festivalgift',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_gifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadrequest',
            name='load',
            field=models.ForeignKey(db_column='load_id', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.load'),
        ),
        migrations.AddField(
            model_name='loadrequest',
            name='requester',
            field=models.ForeignKey(db_column='requester_id', limit_choices_to={'role__in': ['truck_owner', 'transporter']}, on_delete=django.db.models.deletion.CASCADE, related_name='load_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadrequest',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='applied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penalty',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='api.booking'),
        ),
        migrations.AddField(
            model_name='trip',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='api.booking'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='returntripoffer',
            name='original_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_offers', to='api.trip'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.trip'),
        ),
        migrations.AddIndex(
            model_name='vehiclecategory',
            index=models.Index(fields=['vehicle_type', 'is_active'], name='vehicle_cat_vehicle_22d8f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecategory',
            unique_together={('vehicle_type', 'capacity_ton', 'length_ft')},
        ),
        migrations.AddField(
            model_name='pricingslab',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_slabs', to='api.vehiclecategory'),
        ),
        migrations.AddField(
            model_name='load',
            name='required_vehicle_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehiclecategory'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status', 'pickup_date'], name='loads_status_4307a4_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['consignee', 'status'], name='loads_consign_4a975c_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['is_deliverable'], name='loads_is_deli_e598b0_idx'),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddIndex(
            model_name='festivalgift',
            index=models.Index(fields=['festival', 'is_delivered'], name='festival_gi_festiva_6424d3_idx'),
        ),
        migrations.AddIndex(
            model_name='loadrequest',
            index=models.Index(fields=['load', 'status'], name='load_reques_load_id_e767d0_idx'),
        ),
        migrations.AddIndex(
            model_name='loadrequest',
            index=models.Index(fields=['requester', 'status'], name='load_reques_request_1d1112_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loadrequest',
            unique_together={('load', 'requester')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'estimated_delivery_time'], name='trips_status_f5ce9e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['current_lat', 'current_lng'], name='trips_current_ef9d88_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_visible_for_return_search', 'available_capacity_kg'], name='trips_is_visi_6aa770_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['from_lat', 'from_lng', 'destination_lat', 'destination_lng'], name='trips_from_la_da2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='returntripoffer',
            index=models.Index(fields=['from_lat', 'from_lng'], name='return_trip_from_la_b3904b_idx'),
        ),
        migrations.AddIndex(
            model_name='returntripoffer',
            index=models.Index(fields=['is_active', 'available_from'], name='return_trip_is_acti_335661_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['status', 'applied_to'], name='penalties_status_ac22ec_idx'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['penalty_type'], name='penalties_penalty_5c2ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingslab',
            index=models.Index(fields=['vehicle_category', 'is_active'], name='pricing_sla_vehicle_ae0fda_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingslab',
            index=models.Index(fields=['min_distance', 'max_distance'], name='pricing_sla_min_dis_ef99ae_idx'),
        ),
    ]
