# Generated by Django 6.0.1 on 2026-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_booking_bookings_booking_ab1f8c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('phone_verification', 'Phone Verification'), ('login', 'Login')], max_length=20),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'otp_type', 'is_used'], name='otp_verific_email_164e1c_idx'),
        ),
    ]
