# Generated by Django 6.0.1 on 2026-02-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_otp_otp_type_alter_otp_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bilty_url',
            new_name='bilty',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='invoice_url',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='dispute',
            old_name='evidence_url',
            new_name='evidence',
        ),
        migrations.RenameField(
            model_name='kycdocument',
            old_name='file_url',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_image_url',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='vehiclephoto',
            old_name='photo_url',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consignee', 'Consignee'), ('truck_owner', 'Truck Owner'), ('transporter', 'Transporter'), ('corporate', 'Corporate'), ('admin', 'Admin'), ('driver', 'Driver')], default='consignee', max_length=20),
        ),
    ]
